on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: libgolbat.so
          # - os: window-latest
          #   target: libgolbat.lib
          # - os: macos-latest
          #   target: libgolbat.dyn
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: 设定rust版本
        run: rustup override set 1.92.0
      - uses: actions/checkout@v4
      - name: 编译
        run: cargo build -r
      - name: 查看产物
        run: ls -l ./target/release
      - name: 上传
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.target }}
          path: ./target/release/${{ matrix.target }}
      - name: 发布
        run: gh release create --generate-notes ./target/release/${{ matrix.target }}#${{ matrix.target}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
